name: Deploy to Internal Server (Self-Hosted)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # GitHub Actions를 사내망 서버에서 실행

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # GitHub에서 최신 코드 가져오기

      - name: Copy index.html to Nginx directory
        run: cp index.html /var/www/html/
