name: Deploy to Internal Server (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # GitHub Actions를 사내망 서버에서 실행

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # GitHub에서 최신 코드 가져오기

      - name: Get Server Hostname and IP
        run: |
          echo "### Hostname: $(hostname)"
          echo "### Internal IPs:"
          hostname -I
          echo "### Detailed IP Info:"
          ip a | grep 'inet ' | awk '{print $2}'
          echo "### Public IP (if available):"
          curl -s ifconfig.me || echo "Public IP not available"

      - name: Install Nginx
        run: |
          if ! command -v nginx &> /dev/null; then
            sudo yum install -y nginx
            sudo systemctl enable nginx
            sudo systemctl start nginx
          else
            echo "Nginx is already installed."
          fi

      - name: Ensure Nginx directory exists
        run: sudo mkdir -p /var/www/html

      - name: Copy index.html to Nginx directory
        run: sudo cp index.html /usr/share/nginx/html/ # 레포지토리에 있는 index.html 파일을 Nginx 디렉토리로 복사

      - name: Restart Nginx
        run: sudo systemctl restart nginx
